# Site settings
title: "Robin François"
email: anything@r2gf.com
description: ":fr: in :ch: | Prof: IT security engineer | Hobby: Technology
archeology/history/preservation. Mainly computer and video games related. Member of @museebolo."
baseurl: "http://www.r2gf.com"
url: "http://www.r2gf.com"
title_description: ':fr: in :ch:</br>
Prof: IT Sec engineer <a href="https://twitter.com/navixia">@navixia</a></br>
Hobby: Technology archeology/history/preservation.</br>
Mainly computer and video games related.</br>
Member of <a href="https://twitter.com/museebolo">@museebolo</a>.'
title_image: "img/avatar.png"
github_repository: https://github.com/robin-francois
post_limit: 5

# Social usernames/URLs
twitter_username: r2gf_
github_username:  robin-francois
linkedin_link: https://ch.linkedin.com/in/robinfrancois

# Footer
footer_left: "My views are my own, not of my employers.</a>"
footer_right: "Theme based on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
plugins:
    -jemoji
