# Site settings
title: "Robin François"
email: anything@r2gf.com
description: "IT Security, member of the dul.ac CTF team. Loves brezel and to know how things work (to eventually break them)"
baseurl: ""
url: "http://r2gf.com"
title_description: "IT Security Engineer at <a href=\"https://www.navixia.com\">Navixia</a>
Member of the <a href=\"https://twitter.com/dul_ac\">dul.ac CTF team</a> 
Loves brezel and to know how things work (to eventually break them)"
title_image: "img/avatar.png"
github_repository: https://github.com/robin-francois
post_limit: 5

# Social usernames/URLs
twitter_username: r2gf_
github_username:  robin-francois

# Footer
footer_left: "The views expressed on this web site/blog are mine alone and do not necessarily reflect the views of my employer</a>"
footer_right: "Based on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a> by JacobTomlison"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
