# Site settings
title: "Robin François"
email: anything@r2gf.com
description: "IT Security, member of the dul.ac CTF team. Loves brezel and to know how things work (to eventually break them)"
baseurl: "http://www.r2gf.com"
url: "http://www.r2gf.com"
title_description: "IT Security Engineer at <a href=\"https://www.navixia.com\">Navixia</a></br> 
Member of the <a href=\"https://twitter.com/dul_ac\">dul.ac CTF team</a></br> 
Loves brezel and to know how things work (to eventually break them)"
title_image: "img/avatar.png"
github_repository: https://github.com/robin-francois
post_limit: 5

# Social usernames/URLs
twitter_username: r2gf_
github_username:  robin-francois
linkedin_link: https://ch.linkedin.com/in/robinfrancois

# Footer
footer_left: "My views are my own, not of my employers.</a>"
footer_right: "Theme based on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
